<html>
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="../style/global.css" />
		<link rel="stylesheet" type="text/css" href="../style/account.css" />
		<title>Amazonne - Site officiel</title>
	</head>
	<body>
		<header>
			<div id="left_header">
				<h1>Amazonne</h1>
			</div>
			<!-- Menu -->
			<div id="right_header">
				<ul>
					<a href="src/logout.php" id="sign_out_div">
						<li>SIGN OUT</li>
					</a>
				</ul>
			</div>
		</header>
		<div id="main_page">
			<section>
				<?php
						var_dump($_SESSION);
						if (@$_SESSION['logged_on_admin'] === TRUE)
						{
							include_once ('home_admin.phtml');
						}
						else {
							include_once ('home_user.phtml');
						}
				?>
			</section>
			<footer>
				<hr />
				<p>© 2018 - pprikazs & fherbine</p>
			</footer>
		</div>
		<div>
		</div id="back1"></div>
	</body>
</html>
