<?php 	session_start(); ?>

<html>
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="../style/global.css" />
		<link rel="stylesheet" type="text/css" href="../style/cart.css" />
		<title>Amazonne - Site officiel</title>
	</head>
	<body>
		<header>
			<div id="left_header">
				<h1>Amazonne</h1>
			</div>
			<div class="main_menu">
				<ul>
					<div><a href="../index.php"><li>INDEX</li></a></div>
					<div><a href="cart.phtml"><li>CART</li></a></div>
					<div><a href="account.phtml"><li>ACCOUNT</li></a></div>
				</ul>
			</div>
			<div id="right_header">
				<ul>
					<a href="../src/logout.php" id="sign_out_div">
						<li>SIGN OUT</li>
					</a>
				</ul>
			</div>
		</header>
		<div id="main_page">
			<section>
				<?php
					include_once ('cart_user.phtml');
				?>
			</section>
			<footer>
				<hr />
				<p>© 2018 - pprikazs & fherbine</p>
			</footer>
		</div>
		<div>
		</div id="back1"></div>
	</body>
</html>
