<?php
	$bdd_dir_path = ROOT . DS . 'bdd';
	$bdd_file_path = ROOT . DS . 'bdd' . DS . 'article';
	$articles = get_articles($bdd_dir_path, $bdd_file_path);
		foreach ($articles as $article) :
			$article = article_decode($article);
?>
 <?php if ($_GET == NULL || $article['art_categ'] == $_GET['art_categ'] || $_GET['art_categ'] == "All"):?>
	<article class="product_art">
		<div class="art_img">
			<img src="<?= $article['art_img'] ?>" alt="<?= $article['art_title'] ?> " title="<?= $article['art_title'] ?>" /> <!--penser image backup si non donné ... -->
		</div>

		<div class="art_desc">
			<h2 class="art_title"> <?= $article['art_title'] ?></h></h2>
				<p>
					<?= $article['art_desc'] ?>
				</p>
		</div>

		<div class="art_aside">
			<h3 class="art_cost"><?= $article['art_cost'] ?> €</h3>
			<div class="but_div">
				<div class="art_form">
					<div class="art_sub"><a href="src/add_to_cart.php?art_title=<?= $article['art_title'] ?>">ADD TO CART</a></div>
				</div>
				<div class="art_form">
					<div class="art_sub"><a href="">BUY</a></div>
				</div>
			</div>
		</div>
	</article>
	<hr />
<?php endif;?>
<?php endforeach ?>
