<?php
	$bdd_dir_path = ROOT . DS . 'bdd';
	$bdd_file_path = ROOT . DS . 'bdd' . DS . 'article';
	$articles = get_articles($bdd_dir_path, $bdd_file_path);
	foreach ($articles as $article) :
		$article = article_decode($article);
?>
<tr>
    <td><?= $article['art_title'] ?></td>
    <td><?= $article['art_desc'] ?></td>
    <td><?= $article['art_cost'] ?>€</td>
    <td><a href="../src/remove_article.php?art_title=<?= $article['art_title'] ?>">X</a></td>
</tr>
<?php endforeach ?>
