<div id="chk_block">
    <?php
        $bdd_dir_path = ROOT . DS . 'bdd';
        $bdd_file_path = ROOT . DS . 'bdd' . DS . 'categorie';
        $categories = get_categories($bdd_dir_path, $bdd_file_path);
    ?>
        <?php foreach ($categories as $categorie) : ?>
            <?php $categorie = categorie_decode($categorie); ?>
            <?php if ($categorie != "All"):?>
                <div><label for="<?= $categorie ?>"><?= $categorie ?>  <input type="checkbox" name="art_categ" value="<?= $categorie ?>" id="<?= $categorie ?>" class="check_case"/></label></div>
            <?php endif;?>
        <?php endforeach; ?>
</div>
