<div>
	<?php
		$bdd_dir_path = ROOT . DS . 'bdd';
		$bdd_file_path = ROOT . DS . 'bdd' . DS . 'categorie';
		$categories = get_categories($bdd_dir_path, $bdd_file_path);
	?>

	<select name="art_categ" id="art_categ">
		<?php foreach ($categories as $categorie) : ?>
				<?php $categorie = categorie_decode($categorie); ?>
				<option value="<?= $categorie ?>"><?= $categorie ?></option>
		<?php endforeach; ?>
	</select>
</div>
