            <article>
                <h2>Add a product</h2>
                <form method="post" action="../src/create_article.php" id="add_item">
                    <div>
                        <input type="text" name="art_title" class="admin_inp" placeholder="Title" />
                        <input type="text" name="art_img"  class="admin_inp" placeholder="url_img"></input>
                        <select name="art_categ" id="art_categ">
                            <option value="Smartphones">Smartphones</option>
                            <option value="Computers">Computers</option>
                            <option value="Screens">TV & screens</option>
                        </select>
                    </div>

                    <div>
                        <p>Describe Item:</p>
                        <textarea name="art_desc" class="admin_desc"></textarea>
                    </div>

                    <div>
                        <label for="art_cost">€<input type="number" name="art_cost" class="admin_inp" min="0" placeholder="price" id="art_cost" /></label>
                        <input type="submit" name="submit" value="ADD" />
                    </div>
                </form>
            </article>
