            <article>
                <h2>Add a product</h2>
                <form method="post" action="#" id="add_item">
                    <div>
                        <input type="text" name="art_title" class="admin_inp" placeholder="Title" />
                        <select name="art_categ" id="art_categ">
                            <option value="Smartphones">Smartphones</option>
                            <option value="Computers">Computers</option>
                            <option value="Screens">TV & screens</option>
                        </select>
                    </div>

                    <div>
                        <p>Describe Item:</p>
                        <textarea name="art_desc" class="admin_desc"></textarea>
                        <input type="text" name="art_img" placeholder="url_img"></input>
                    </div>

                    <div>
                        <div><input type="number" name="art_cost" class="admin_inp" min="0" placeholder="price" /><label>€</label></div>
                        <input type="submit" name="submit" value="ADD" />
                    </div>
                </form>
            </article>
