<article>
	<h2>Account settings:</h2>
	<br />
	<div class="user_ablock1">
		<div class="user_ablock2">
			<h3>Change password</h3>
			<form method="post" action="#">
				<input type="text" name="login" placeholder="Login" /> <br/>
				<input type="password" name="oldpw" placeholder="Current password" /><br/>
				<input type="password" name="newpw" placeholder="New password" /><br/>
				<input type="submit" name="submit" value="CHANGE" />
			</form>
		</div>
		<div class="user_ablock2">
			<h3>Delete Account</h3>
			<p><b>Note : </b>This action is irreversible, after clicking on this cross your account will be destroy definitely !</p>
			<div class="cross_container"><a href="#">X</a></div>
		</div>
	</div>
</article>
<br />